# Generated by Django 5.0.2 on 2024-02-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gpa',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
