# Generated by Django 5.0.2 on 2024-02-18 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_gpa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Last_name',
            new_name='last_name',
        ),
    ]
